In [ ]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd
import numpy as np #numerical python

In [ ]:
df = pd.read_csv('Churn_Modelling.csv')

In [ ]:
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [ ]:
df.head() #IF no argumnets passed then it will give 5

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [ ]:
df.head(10)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
5,6,15574012,Chu,645,Spain,Male,44,8,113755.78,2,1,0,149756.71,1
6,7,15592531,Bartlett,822,France,Male,50,7,0.00,2,1,1,10062.80,0
7,8,15656148,Obinna,376,Germany,Female,29,4,115046.74,4,1,0,119346.88,1
8,9,15792365,He,501,France,Male,44,4,142051.07,2,0,1,74940.50,0
9,10,15592389,H?,684,France,Male,27,2,134603.88,1,1,1,71725.73,0

In [ ]:
df.tail()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [ ]:
df.describe() #only numerical columns

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.00000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,5000.50000,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,2886.89568,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.00000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,2500.75000,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,5000.50000,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,7500.25000,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,10000.00000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

In [ ]:
df.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [ ]:
df.T

,0,1,2,3,4,5,6,7,8,9,...,9990,9991,9992,9993,9994,9995,9996,9997,9998,9999
RowNumber,1,2,3,4,5,6,7,8,9,10,...,9991,9992,9993,9994,9995,9996,9997,9998,9999,10000
CustomerId,15634602,15647311,15619304,15701354,15737888,15574012,15592531,15656148,15792365,15592389,...,15798964,15769959,15657105,15569266,15719294,15606229,15569892,15584532,15682355,15628319
Surname,Hargrave,Hill,Onio,Boni,Mitchell,Chu,Bartlett,Obinna,He,H?,...,Nkemakonam,Ajuluchukwu,Chukwualuka,Rahman,Wood,Obijiaku,Johnstone,Liu,Sabbatini,Walker
CreditScore,619,608,502,699,850,645,822,376,501,684,...,714,597,726,644,800,771,516,709,772,792
Geography,France,Spain,France,France,Spain,Spain,France,Germany,France,France,...,Germany,France,Spain,France,France,France,France,France,Germany,France
Gender,Female,Female,Female,Female,Female,Male,Male,Female,Male,Male,...,Male,Female,Male,Male,Female,Male,Male,Female,Male,Female
Age,42,41,42,39,43,44,50,29,44,27,...,33,53,36,28,29,39,35,36,42,28
Tenure,2,1,8,1,2,8,7,4,4,2,...,3,4,2,7,2,5,10,7,3,4
Balance,0.0,83807.86,159660.8,0.0,125510.82,113755.78,0.0,115046.74,142051.07,134603.88,...,35016.6,88381.21,0.0,155060.41,0.0,0.0,57369.61,0.0,75075.31,130142.79
NumOfProducts,1,1,3,2,1,2,2,4,2,1,...,1,1,1,1,2,2,1,1,2,1
HasCrCard,1,0,1,0,1,1,1,1,0,1,...,1,1,1,1,0,1,1,0,1,1
IsActiveMember,1,1,0,0,1,0,1,0,1,1,...,0,0,0,0,0,0,1,1,0,0
EstimatedSalary,101348.88,112542.58,113931.57,93826.63,79084.1,149756.71,10062.8,119346.88,74940.5,71725.73,...,53667.08,69384.71,195192.4,29179.52,167773.55,96270.64,101699.77,42085.58,92888.52,38190.78
Exited,1,0,1,0,0,1,0,1,0,0,...,0,1,0,0,0,0,0,1,1,0

In [ ]:
#sorting
df.sort_values('Age')

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
1678,1679,15569178,Kharlamov,570,France,Female,18,4,82767.42,1,1,0,71811.90,0
4556,4557,15796231,Nwankwo,681,France,Female,18,1,98894.39,1,1,1,9596.40,0
9520,9521,15673180,Onyekaozulu,727,Germany,Female,18,2,93816.70,2,1,0,126172.11,0
9526,9527,15665521,Chiazagomekpele,642,Germany,Male,18,5,111183.53,2,0,1,10063.75,0
9572,9573,15641688,Collier,644,Spain,Male,18,7,0.00,1,0,1,59645.24,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3531,3532,15653251,Hickey,408,France,Female,84,8,87873.39,1,0,0,188484.52,1
3033,3034,15578006,Yao,787,France,Female,85,10,0.00,2,1,1,116537.96,0
2458,2459,15813303,Rearick,513,Spain,Male,88,10,0.00,2,1,1,52952.24,0
6443,6444,15764927,Rogova,753,France,Male,92,3,121513.31,1,0,1,195563.99,0
6759,6760,15660878,T'ien,705,France,Male,92,1,126076.24,2,1,1,34436.83,0

In [ ]:
new_df= df.sort_values('Age')

In [ ]:
new_df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
1678,1679,15569178,Kharlamov,570,France,Female,18,4,82767.42,1,1,0,71811.90,0
4556,4557,15796231,Nwankwo,681,France,Female,18,1,98894.39,1,1,1,9596.40,0
9520,9521,15673180,Onyekaozulu,727,Germany,Female,18,2,93816.70,2,1,0,126172.11,0
9526,9527,15665521,Chiazagomekpele,642,Germany,Male,18,5,111183.53,2,0,1,10063.75,0
9572,9573,15641688,Collier,644,Spain,Male,18,7,0.00,1,0,1,59645.24,1

In [ ]:
df['Balance']

0            0.00
1        83807.86
2       159660.80
3            0.00
4       125510.82
          ...
9995         0.00
9996     57369.61
9997         0.00
9998     75075.31
9999    130142.79
Name: Balance, Length: 10000, dtype: float64

In [ ]:
df.Balance #doesnt work if there is space in column name

0            0.00
1        83807.86
2       159660.80
3            0.00
4       125510.82
          ...
9995         0.00
9996     57369.61
9997         0.00
9998     75075.31
9999    130142.79
Name: Balance, Length: 10000, dtype: float64

In [ ]:
df['Balance'] + 1000

0         1000.00
1        84807.86
2       160660.80
3         1000.00
4       126510.82
          ...
9995      1000.00
9996     58369.61
9997      1000.00
9998     76075.31
9999    131142.79
Name: Balance, Length: 10000, dtype: float64

In [ ]:
df['New Balance'] = df['Balance'] + 1000 #assigning the values to new column

In [ ]:
df.head(5)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,New Balance
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1,1000.00
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,84807.86
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,160660.80
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0,1000.00
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,126510.82

In [ ]:
df['Random Column'] = 'Good day'

In [ ]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,New Balance,Random Column
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1,1000.00,Good day
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,84807.86,Good day
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,160660.80,Good day
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0,1000.00,Good day
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,126510.82,Good day

In [ ]:
#how to acess rows n columns
#wanna access 10th to 13th
df[10:13]

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,New Balance,Random Column
10,11,15767821,Bearce,528,France,Male,31,6,102016.72,2,0,0,80181.12,0,103016.72,Good day
11,12,15737173,Andrews,497,Spain,Male,24,3,0.00,2,1,0,76390.01,0,1000.00,Good day
12,13,15632264,Kay,476,France,Female,34,10,0.00,2,1,0,26260.98,0,1000.00,Good day

In [ ]:
#where age is greater than 50
age_50= df[df.Age > 50]

In [ ]:
len(age_50)

1261

In [ ]:
len(df)

10000

In [ ]:
#fill null values- fillna
df['Age'].fillna(15)

0       42
1       41
2       42
3       39
4       43
        ..
9995    39
9996    35
9997    36
9998    42
9999    28
Name: Age, Length: 10000, dtype: int64

In [ ]:
#remove columns
new_df.pop('RowNumber')

1678    1679
4556    4557
9520    9521
9526    9527
9572    9573
        ...
3531    3532
3033    3034
2458    2459
6443    6444
6759    6760
Name: RowNumber, Length: 10000, dtype: int64

In [ ]:
new_df.pop('CustomerId')

1678    15569178
4556    15796231
9520    15673180
9526    15665521
9572    15641688
          ...
3531    15653251
3033    15578006
2458    15813303
6443    15764927
6759    15660878
Name: CustomerId, Length: 10000, dtype: int64

In [ ]:
new_df.head()

,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
1678,Kharlamov,570,France,Female,18,4,82767.42,1,1,0,71811.90,0
4556,Nwankwo,681,France,Female,18,1,98894.39,1,1,1,9596.40,0
9520,Onyekaozulu,727,Germany,Female,18,2,93816.70,2,1,0,126172.11,0
9526,Chiazagomekpele,642,Germany,Male,18,5,111183.53,2,0,1,10063.75,0
9572,Collier,644,Spain,Male,18,7,0.00,1,0,1,59645.24,1

In [ ]:
df['Balance']

0            0.00
1        83807.86
2       159660.80
3            0.00
4       125510.82
          ...
9995         0.00
9996     57369.61
9997         0.00
9998     75075.31
9999    130142.79
Name: Balance, Length: 10000, dtype: float64

In [ ]:
df['square_Balance'] = df['Balance'].apply(np.sqrt)

In [ ]:
df

In [ ]:
df['Age'].dropna()

0       42
1       41
2       42
3       39
4       43
        ..
9995    39
9996    35
9997    36
9998    42
9999    28
Name: Age, Length: 10000, dtype: int64

In [ ]:
#concat
df1= pd.DataFrame(
    {'A':['A0','A1','A2','A3'],
    'B':['B0','B1','B2','B3'],
    'C':['C0','C1','C2','C3'],
    'D':['D0','D1','D2','D3']
})

In [ ]:
#concat
df2= pd.DataFrame(
    {'A':['A4','A5','A6','A7'],
    'B':['B4','B5','B6','B7'],
    'C':['C4','C5','C6','C7'],
    'D':['D4','D5','D6','D7']
})

In [ ]:
df1

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [ ]:
df2

    A   B   C   D
0  A4  B4  C4  D4
1  A5  B5  C5  D5
2  A6  B6  C6  D6
3  A7  B7  C7  D7

In [ ]:
result = pd.concat([df1, df2])

In [ ]:
result

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3
0  A4  B4  C4  D4
1  A5  B5  C5  D5
2  A6  B6  C6  D6
3  A7  B7  C7  D7

In [ ]:
merge_df = pd.merge(df1, df2, on= 'C', how= 'right')

In [ ]:
merge_df

   A_x  B_x   C  D_x A_y B_y D_y
0  NaN  NaN  C4  NaN  A4  B4  D4
1  NaN  NaN  C5  NaN  A5  B5  D5
2  NaN  NaN  C6  NaN  A6  B6  D6
3  NaN  NaN  C7  NaN  A7  B7  D7

In [ ]:
#loc vs iloc
#loc gets rows with particular labels
#iloc gets rows with integer locations

In [ ]:
s = pd.Series(list("abcdef"),index=[49,48,47,0,1,2])
s

49    a
48    b
47    c
0     d
1     e
2     f
dtype: object

In [ ]:
s.loc[0] #value at index label 0

'd'

In [ ]:
s.iloc[0] #value at index location 0

'a'

In [ ]:
s.loc[0:1] #rows at index lables between 0 and 1 (inclusive)

0    d
1    e
dtype: object

In [ ]:
s.iloc[0:1] #rows at location 0 and 1(exclusive)

49    a
dtype: object

**Numpy**

In [ ]:
#data analytics-numerical featuers- we read using pandas
#library used for computational and processing of single and multi dimensional arrays of elements

In [2]:
pip install numpy

Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)

In [1]:
import numpy as np

In [ ]:
#creating an array
a = np.array([1,2,3]) #here its int
print(a)

[1 2 3]

In [ ]:
type(a) #numpy n dimensional array

numpy.ndarray

In [ ]:
b = np.array([1,2,3], dtype = float) #here we r changing it to float hehe
print(b)

[1. 2. 3.]

In [ ]:
c = np.array([1,2,3], dtype = str) #here sting
print(c)

['1' '2' '3']

In [ ]:
len(a)

3

In [ ]:
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]

In [ ]:
type(b)

numpy.ndarray

In [ ]:
len(b) #it wont be 6 it will be 2 coz 2 objects

2

In [ ]:
c = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

In [ ]:
#to chk dimensions
a.ndim

1

In [ ]:
c.ndim

2

In [ ]:
b.ndim

2

In [ ]:
a

array([1, 2, 3])

In [ ]:
c.shape

(3, 3)

In [ ]:
c.dtype #datatype

dtype('int64')

In [ ]:
#accessing or changing
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]

In [ ]:
a.ndim

2

In [ ]:
a[0,4]

np.int64(5)

In [ ]:
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
#zeros and ones method in numpy

In [ ]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.ones((3,3), dtype='int32')

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [ ]:
np.zeros((3,3), dtype='str')

array([['', '', ''],
       ['', '', ''],
       ['', '', '']], dtype='<U1')

In [ ]:
np.full((3,3), 50, dtype='float64')

array([[50., 50., 50.],
       [50., 50., 50.],
       [50., 50., 50.]])

In [ ]:
np.full((3,3), 50, dtype='float')

array([[50., 50., 50.],
       [50., 50., 50.],
       [50., 50., 50.]])

In [ ]:
np.random.rand(4,4)

array([[0.74108169, 0.1216495 , 0.1907539 , 0.23575056],
       [0.33880555, 0.83800507, 0.01392331, 0.15874245],
       [0.58000405, 0.79691694, 0.36527415, 0.5763715 ],
       [0.41040335, 0.93317115, 0.41870461, 0.2858868 ]])

In [ ]:
np.random.randint(-4, 1, size=(3,3))

array([[-4, -3,  0],
       [-3, -3,  0],
       [-2, -1, -2]])

In [ ]:
np.random.randint(-5,0, size=(3,3))

array([[-5, -4, -2],
       [-5, -4, -1],
       [-4, -5, -5]])

In [ ]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Question #1
Extract all the first 3 rows of the last 5 columns in a given numpy 2D array 'a'?

In [ ]:
a = np.array([[1,2,3,4,5,6],
             [10,20,30,40,50,60],
             [12,12,12,12,12,12],
             [11,21,31,41,51,61],
             [13,24,34,44,54,64]])

In [ ]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [10, 20, 30, 40, 50, 60],
       [12, 12, 12, 12, 12, 12],
       [11, 21, 31, 41, 51, 61],
       [13, 24, 34, 44, 54, 64]])

In [22]:
a[ :3, -5: ]

array([[ 2,  3,  4,  5,  6],
       [20, 30, 40, 50, 60],
       [12, 12, 12, 12, 12]])

In [3]:
#question 2
n=5
z= np.zeros((n,n), dtype= 'int')

In [4]:
print(z)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]

In [5]:
z[n//2, :] =1
z[:, n//2] = 1

In [6]:
print(z)

[[0 0 1 0 0]
 [0 0 1 0 0]
 [1 1 1 1 1]
 [0 0 1 0 0]
 [0 0 1 0 0]]

In [3]:
#arithmetic

a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]

In [8]:
a+2

array([3, 4, 5, 6, 7])

In [6]:
a**3

array([  1,   8,  27,  64, 125])

In [8]:
print(a.mean())

3.0

In [6]:
print(np.min(a))
print(np.max(a))

1
5

In [9]:
print(np.sum(a))

15